create table if not exists public.users (
  id bigint generated by default as identity primary key,
  username text unique not null,
  email text,
  password text not null,
  isadmin boolean default false,
  registereddate date default now()
);

create table if not exists public.games (
  id bigint generated by default as identity primary key,
  name text not null,
  image text
);

create table if not exists public.servers (
  id bigint generated by default as identity primary key,
  name text not null,
  gameid bigint references public.games(id) on delete cascade
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  server text not null,
  category text not null,
  unit text not null,
  price numeric not null,
  stock integer not null,
  seller text not null,
  gameid bigint references public.games(id) on delete set null
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  content text not null,
  enabled boolean default true
);

create table if not exists public.advertisements (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  image text,
  enabled boolean default true
);

insert into public.users (username, email, password, isadmin, registereddate)
values ('admin','admin@system.com','admin',true,'2024-01-01')
on conflict (username) do nothing;

alter table public.users enable row level security;
alter table public.games enable row level security;
alter table public.servers enable row level security;
alter table public.products enable row level security;
alter table public.notifications enable row level security;
alter table public.advertisements enable row level security;

create policy "Allow read for anon" on public.users for select using (true);
create policy "Allow read for anon" on public.games for select using (true);
create policy "Allow read for anon" on public.servers for select using (true);
create policy "Allow read for anon" on public.products for select using (true);
create policy "Allow read for anon" on public.notifications for select using (true);
create policy "Allow read for anon" on public.advertisements for select using (true);

create policy "Allow insert for service role only" on public.users for insert with check (false);
create policy "Allow insert for anon" on public.games for insert with check (true);
create policy "Allow insert for anon" on public.servers for insert with check (true);
create policy "Allow insert for anon" on public.products for insert with check (true);
create policy "Allow insert for anon" on public.notifications for insert with check (true);
create policy "Allow insert for anon" on public.advertisements for insert with check (true);

create policy "Allow delete for anon" on public.games for delete using (true);
create policy "Allow delete for anon" on public.servers for delete using (true);
create policy "Allow delete for anon" on public.products for delete using (true);
create policy "Allow delete for anon" on public.notifications for delete using (true);
create policy "Allow delete for anon" on public.advertisements for delete using (true);
