create table if not exists public.users (
  id bigint generated by default as identity primary key,
  username text unique not null,
  email text,
  password text not null,
  isadmin boolean default false,
  registereddate date default now()
);

create table if not exists public.games (
  id bigint generated by default as identity primary key,
  name text not null,
  image text
);

create table if not exists public.servers (
  id bigint generated by default as identity primary key,
  name text not null,
  gameid bigint references public.games(id) on delete cascade
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  server text not null,
  category text not null,
  unit text not null,
  price numeric not null,
  stock integer not null,
  seller text not null,
  gameid bigint references public.games(id) on delete set null
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  content text not null,
  enabled boolean default true
);

create table if not exists public.advertisements (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  image text,
  enabled boolean default true
);

insert into public.users (username, email, password, isadmin, registereddate)
values ('admin','admin@system.com','admin',true,'2024-01-01')
on conflict (username) do nothing;

alter table public.users enable row level security;
alter table public.games enable row level security;
alter table public.servers enable row level security;
alter table public.products enable row level security;
alter table public.notifications enable row level security;
alter table public.advertisements enable row level security;

drop policy if exists "Allow read for anon" on public.users;
create policy "Allow read for anon" on public.users for select using (true);
drop policy if exists "Allow read for anon" on public.games;
drop policy if exists "Allow read for anon" on public.servers;
drop policy if exists "Allow read for anon" on public.products;
drop policy if exists "Allow read for anon" on public.notifications;
drop policy if exists "Allow read for anon" on public.advertisements;
create policy "Allow read for anon" on public.games for select using (true);
create policy "Allow read for anon" on public.servers for select using (true);
create policy "Allow read for anon" on public.products for select using (true);
create policy "Allow read for anon" on public.notifications for select using (true);
create policy "Allow read for anon" on public.advertisements for select using (true);

drop policy if exists "Allow insert for service role only" on public.users;
drop policy if exists "Allow insert for anon" on public.games;
drop policy if exists "Allow insert for anon" on public.servers;
drop policy if exists "Allow insert for anon" on public.products;
drop policy if exists "Allow insert for anon" on public.notifications;
drop policy if exists "Allow insert for anon" on public.advertisements;
drop policy if exists "Allow insert for anon" on public.users;
create policy "Allow insert for service role only" on public.users for insert with check (false);
create policy "Allow insert for anon" on public.users for insert with check (true);
create policy "Allow insert for anon" on public.games for insert with check (true);
create policy "Allow insert for anon" on public.servers for insert with check (true);
create policy "Allow insert for anon" on public.products for insert with check (true);
create policy "Allow insert for anon" on public.notifications for insert with check (true);
create policy "Allow insert for anon" on public.advertisements for insert with check (true);

drop policy if exists "Allow delete for anon" on public.games;
drop policy if exists "Allow delete for anon" on public.servers;
drop policy if exists "Allow delete for anon" on public.products;
drop policy if exists "Allow delete for anon" on public.notifications;
drop policy if exists "Allow delete for anon" on public.advertisements;
create policy "Allow delete for anon" on public.games for delete using (true);
create policy "Allow delete for anon" on public.servers for delete using (true);
create policy "Allow delete for anon" on public.products for delete using (true);
create policy "Allow delete for anon" on public.notifications for delete using (true);
create policy "Allow delete for anon" on public.advertisements for delete using (true);
drop policy if exists "Allow delete for anon" on public.users;
create policy "Allow delete for anon" on public.users for delete using (true);

drop policy if exists "Allow update for anon" on public.games;
drop policy if exists "Allow update for anon" on public.servers;
drop policy if exists "Allow update for anon" on public.products;
drop policy if exists "Allow update for anon" on public.notifications;
drop policy if exists "Allow update for anon" on public.advertisements;
create policy "Allow update for anon" on public.games for update using (true) with check (true);
create policy "Allow update for anon" on public.servers for update using (true) with check (true);
create policy "Allow update for anon" on public.products for update using (true) with check (true);
create policy "Allow update for anon" on public.notifications for update using (true) with check (true);
create policy "Allow update for anon" on public.advertisements for update using (true) with check (true);
drop policy if exists "Allow update for anon" on public.users;
create policy "Allow update for anon" on public.users for update using (true) with check (true);

-- Seed initial data
-- Games
insert into public.games (name, image)
select '아이온2', 'img/아이온.jpg'
where not exists (select 1 from public.games where name = '아이온2');

insert into public.games (name, image)
select '리니지2', 'img/리니지2.jpg'
where not exists (select 1 from public.games where name = '리니지2');

insert into public.games (name, image)
select '리니지M', 'img/리니지m.jpg'
where not exists (select 1 from public.games where name = '리니지M');

-- Servers for 아이온2
insert into public.servers (name, gameid)
select v.name, g.id
from (values ('天启[天族]'), ('荣耀[魔族]'), ('永恒[天族]')) as v(name)
join public.games g on g.name = '아이온2'
where not exists (
  select 1 from public.servers s where s.name = v.name and s.gameid = g.id
);

-- Products for 아이온2
insert into public.products (name, server, category, unit, price, stock, seller, gameid)
select v.name, v.server, v.category, v.unit, v.price, v.stock, v.seller, g.id
from (
  values 
    ('满级神装 3000战力','天启[天族]','装备','件',899,5,'装备专卖','아이온2'),
    ('游戏币 手工打金','荣耀[魔族]','游戏币','万',320,999,'游戏币商','아이온2'),
    ('满级账号 2800战力','永恒[天族]','账号','个',1599,1,'账号商','아이온2')
) as v(name, server, category, unit, price, stock, seller, game_name)
join public.games g on g.name = v.game_name
where not exists (
  select 1 from public.products p 
  where p.name = v.name and p.server = v.server and p.gameid = g.id
);

-- Notifications
insert into public.notifications (content, enabled)
select v.content, v.enabled
from (values 
  ('欢迎来到游戏交易平台！', true),
  ('现在注册即可获得5%的折扣！', true)
) as v(content, enabled)
where not exists (select 1 from public.notifications n where n.content = v.content);

-- Advertisements
insert into public.advertisements (title, content, image, enabled)
select v.title, v.content, v.image, v.enabled
from (values
  ('新服开启', '新服天启[天族]已开启，欢迎加入！', '', true),
  ('限时优惠', '游戏币购买享受9折优惠，限时3天！', '', true)
) as v(title, content, image, enabled)
where not exists (select 1 from public.advertisements a where a.title = v.title);
